Replace grammar by `antlr/grammars-v4`'s
Quantco/pytsql pull request #73
Opened 2023-03-20 09:26 UTC by svengiegerich

### Motivation

Microsoft has never published a full open specification for T-SQL, so each grammar "replication" of Transact-SQL (TSQL) is incomplete. The project's current grammar is (mainly) based on https://github.com/antlr/codebuff/blob/master/grammars/org/antlr/codebuff/tsql.g4, which was last updated in 2016. 

Consequently, in my projects, I encountered several (elements of) SQL statements that `pytsql` was or is currently incapable of parsing - i.e., it's not possible to execute them with `pytsql.` 
Examples are PR #51, #59, or, more recently, I tried to parse `DATETIME2` and `STRING_AGG()` without luck.

In the past, we always manually adjusted our `.g4` grammar - e.g., PR #33. However, this solves the problem, namely that the grammar has (apparent) gaps, only fragmentarily. Also, manual changes to the grammar generally make the package harder to maintain and may need to be more focused on the actual focus of the package.

Fortunately, however, a relatively actively maintained grammar with significantly greater functionality exists: https://github.com/antlr/grammars-v4/tree/master/sql/tsql **(*)**. It is even an evolution of our 2016 version. I propose to base our grammar on it instead.

I would even propose moving all future grammar extensions completely to this external repository to keep our package as light as possible.

👍 Pros:
- Grammar **(*)** ships much more valid syntax 
- 👉 `pytsql` get's "leaner" & can focus less on grammar definition
- 👉  In effect, more TSQL statements get parseable

👎 Cons:
- Grammar **(*)** has _more_ false positives. That is, sometimes invalid statements are still parsed successfully
  - example (1): `USEE master` does not raise an issue
  - example (2): in rare cases `\N GO` is not recognised correctly; see https://github.com/antlr/grammars-v4/issues/3275 - adding ';' solves it for `isolate_top_level_statements=False`
  - however, despite `pytsql` "executing" these statements, sqlcmd in the end still handles them correctly...
  - ... so it may boils down to which tools should generate the error message (?)

### Changes

Replace `tsql.g4` by https://github.com/antlr/grammars-v4/tree/master/sql/tsql **(*)**.

- Modify grammar **(*)** slightly: 
  - certain [rule element labels](https://github.com/antlr/antlr4/blob/master/doc/parser-rules.md) are protected within C++ 
  - 👉 rename label `<x>` to `<x>_label` (similar to PR #28)
- Generate new targets
- Adjust `tsql.py`
- Adjust tests:
  - +1: some minor flaws in current test queries were not flagged with our current grammar
  - -1: remove some tests that flagged wrong TSQL statements
- Adjust documentation

---

Example of a false positive parsing of grammar **(*)**:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/1476077/226296513-81837b0d-3f64-48c9-b65b-ed7998de61c6.png">

2023-03-24 08:14 UTC, xhochy commented on src/pytsql/grammar/cpp_src/TSqlLexer.h
> +
```suggestion
#undef PLATFORM
```

2023-03-24 08:14 UTC, xhochy commented on src/pytsql/grammar/cpp_src/TSqlLexer.h
> +
@svengiegerich very wild guess, let's see

2023-03-24 08:17 UTC, xhochy commented
For faster feedback this should also has Windows unit tests ;)

2023-03-24 18:20 UTC, SimeonStoykovQC requested changes
Sadly, at the moment, the new grammar doesn't seem to accommodate the current use cases we have for pytsql internally. See one example in #74 .

Also, regarding [this](https://github.com/antlr/grammars-v4/issues/3275#issuecomment-1474999841):
> The second moment to note is that indeed it seems grammar in this repo is not correct about dividing file to batches by GO-statements.

I would be a bit worried, because this is one of the most important uses of `pytsql` for us.

2023-03-26 07:41 UTC, kklein reviewed
I think there is a great ambition behind this undertaking!

Moving forward, three rather high-level things are not yet crystal clear to me:

1. I haven't seen a license for the source of the new grammar at first sight. Are we sure we can use their code? If yes, should we give them credits in the Readme?

2. You suggested that this change would make pytsql leaner and focalize attention on topics other than the grammar. Does that mean you intend to use a submodule or the like eventually? If no, what is the suggested mode of operation: should pytsql contributors always seek to contribute changes to the grammar via the `antlr` repository and then copy the grammar to pytsql, once merged?

2023-03-26 07:41 UTC, kklein commented on tests/unit/test_split.py
> -    INTO linked_server.db.schm.table1
Based on the description of the PR as well as the commit messages it's not obvious to me why we would no longer be able to support this.

2023-03-26 07:41 UTC, kklein commented on tests/unit/test_py_vs_cpp.py
> +    py_context_children = list(py_context.getChildren())
Was there a clear cut problem with using the `children` attribute here and in the following lines or was this syntactic preference?

2023-03-26 07:41 UTC, kklein commented on tests/unit/test_split.py
> +    seed = """DECLARE @td            VARCHAR(20)   = CONVERT(VARCHAR, GETDATE(), 112)
Thanks to your comment, I could follow that the change in `test_dynamics` is due to https://github.com/antlr/grammars-v4/issues/3275. 

It's not clear to me why this change - and all other changes removing semicolons - is necessary. Was the previous grammar too lax; do we actually think this is an illegitimate statement? Or is this an unfortunate confinement of the newly proposed grammar?

2023-03-30 06:25 UTC, ivergara reviewed
Good job!

2023-03-30 06:25 UTC, ivergara commented on src/pytsql/grammar/adjust_antlrs_grammar.py
> +@click.group()
Just curiosity, why do you create two groups with one command each instead of just one group with the commands

2023-03-30 06:25 UTC, ivergara commented on src/pytsql/grammar/adjust_antlrs_grammar.py
> +import click
I find it interesting that it seems pre-commit is not doing its job because this is a violation of isort config.

2023-04-03 06:14 UTC, merged